name: Sync To Gitee  
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      #   # 步骤1 拉取仓库代码
      # - name: Checkout # 步骤名称
      #   uses: actions/checkout@v2 
        
      # # 步骤2 给当前服务器安装node
      # - name: use node
      #   uses: actions/setup-node@v2
      #   with: 
      #     node-version: 14 # node版本
      # - name: Install and Build
      #   run: npm install && npm run docs:build
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:CatsAndMice/vuepress-blog.git"
          destination-repo: "git@gitee.com:JsHai/vuepress-blog.git"
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 13034833806
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: JsHai/vuepress-blog
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master